/**
 * Tree serializers
 * Convert TreeNode structure to Markdown with format version and updated shortcuts
 */

import { TreeNode } from "../types";
import * as path from "path";

export class TreeSerializer {
  /**
   * Serialize tree to Markdown format with all required metadata
   */
  static toMarkdown(
    tree: TreeNode,
    rootPath: string = "",
    folderName: string = "",
  ): string {
    const now = new Date();
    const dateStr = now.toLocaleString("en-US", {
      month: "numeric",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "numeric",
      second: "numeric",
      hour12: true,
    });

    let output = "";

    // Format version (for forward compatibility)
    output += "<!-- FILETREEFORGE FORMAT v1 -->\n\n";

    // Required headers
    output += `# ROOT FOLDER : ${folderName || tree.name}\n`;
    output += `# GENERATED : ${dateStr}\n`;
    output += `# ROOT PATH : ${rootPath}\n\n`;

    if (tree.children && tree.children.length > 0) {
      output += this.serializeChildren(tree.children, "", true);
    }

    // Required footer with updated shortcuts
    output += "\n# Generated by FILETREEFORGE\n\n";
    output += "# Shortcuts\n";
    output += "# Ctrl + Shift + Enter → Preview\n";
    output += "# Ctrl + Enter → Apply Changes\n\n";
    output += "# IMPORTANT RULES\n";
    output +=
      "# - For renames: change the file name and KEEP the <!-- id: xxxxxxxx -->\n";
    output +=
      "# - Changing a file name WITHOUT an id = delete old + create new\n";

    return output;
  }

  /**
   * Serialize children with tree symbols
   */
  private static serializeChildren(
    children: TreeNode[],
    prefix: string,
    isRoot: boolean = false,
  ): string {
    let output = "";

    for (let i = 0; i < children.length; i++) {
      const child = children[i];
      const isLast = i === children.length - 1;

      // Determine tree symbol
      const symbol = isLast ? "└─" : "├─";
      const childPrefix = isLast ? "   " : "│  ";

      // Add node with UUID comment (short version - 8 chars)
      const suffix = child.type === "folder" ? "/" : "";
      const shortId = child.id.length > 8 ? child.id.substring(0, 8) : child.id;
      const idComment = ` <!-- id: ${shortId} -->`;
      output += `${prefix}${symbol} ${child.name}${suffix}${idComment}\n`;

      // Recursively add children
      if (child.children && child.children.length > 0) {
        output += this.serializeChildren(
          child.children,
          prefix + childPrefix,
          false,
        );
      }
    }

    return output;
  }

  /**
   * Get paths from tree (for debugging/listing)
   */
  static getAllPaths(tree: TreeNode, prefix: string = ""): string[] {
    const paths: string[] = [];

    if (tree.children) {
      for (const child of tree.children) {
        const childPath = prefix ? `${prefix}/${child.name}` : child.name;
        paths.push(childPath);

        if (child.children) {
          paths.push(...this.getAllPaths(child, childPath));
        }
      }
    }

    return paths;
  }
}
